'use strict';

const assert = require('node:assert/strict');
const {execFileSync} = require('node:child_process');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const {test} = require('node:test');
const {diagnose} = require('./diagnostics.cjs');
const {analyzeAccess} = require('./accessibility.cjs');
const {readParts, render} = require('./generate-parts-docs.cjs');

const root = path.resolve(__dirname, '..');
const expectedIds = [
  'balcony.planted', 'bed.alcove', 'core.lift', 'entrance.canopy', 'facade.pier-bay',
  'facade.punched-window', 'kitchen.run', 'roof.parapet', 'roof.screen', 'seat.pair',
  'sign.wall-framed', 'stair.straight', 'stair.switchback'
];

function gsonJar(directory) {
  if (!fs.existsSync(directory)) return null;
  for (const entry of fs.readdirSync(directory, {withFileTypes: true})) {
    const candidate = path.join(directory, entry.name);
    if (entry.isDirectory()) {
      const found = gsonJar(candidate);
      if (found) return found;
    } else if (/^gson-.*\.jar$/.test(entry.name)) return candidate;
  }
  return null;
}

function compiler() {
  const javaHome = process.env.JAVA_HOME || path.join(root, 'preview', '.workspace', 'java21');
  const java = process.platform === 'win32' ? path.join(javaHome, 'bin', 'java.exe') : path.join(javaHome, 'bin', 'java');
  const executable = fs.existsSync(java) ? java : 'java';
  const env = {...process.env, JAVA_HOME: javaHome};
  execFileSync('./gradlew', ['--no-daemon', '-q', 'classes'], {cwd: root, env, stdio: 'pipe'});
  const jar = gsonJar(path.join(os.homedir(), '.gradle', 'caches', 'modules-2', 'files-2.1', 'com.google.code.gson', 'gson'));
  if (!jar) throw new Error('Could not locate Gson after Gradle build');
  return {executable, classpath: [path.join(root, 'build/classes/java/main'), path.join(root, 'build/resources/main'), jar].join(path.delimiter)};
}

const stateByRole = {
  air: 'minecraft:air',
  glass: 'minecraft:glass_pane',
  railing: 'minecraft:iron_bars',
  screen: 'minecraft:iron_bars',
  'stair-up-south': 'minecraft:stone_brick_stairs[facing=south,half=bottom,shape=straight,waterlogged=false]',
  shade: 'minecraft:oak_trapdoor[facing=north,half=top,open=false,powered=false,waterlogged=false]',
  sign: 'minecraft:oak_wall_sign[facing=north,waterlogged=false]',
  bed: 'minecraft:red_bed[facing=north,occupied=false,part=foot]'
};

function palette(part) {
  const result = {};
  for (const parameter of Object.values(part.parameters)) {
    if (parameter.type === 'material') result[parameter.default] = stateByRole[parameter.default] || 'minecraft:stone';
  }
  return result;
}

function plan(part, params = {}, at = part.test.at) {
  return {
    schema_version: 2,
    plan_id: 'part-fixture',
    revision: 'check',
    name: `Part fixture ${part.id}`,
    dimensions: {x: 48, y: 64, z: 48},
    palette: palette(part),
    components: [{id: 'caller', role: 'fixture', origin: [0, 0, 0], operations: [{op: 'call', part: part.id, at, params}]}]
  };
}

function compile(compilerCommand, value) {
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), 'praya-builder-part-'));
  const file = path.join(directory, 'fixture.json');
  try {
    fs.writeFileSync(file, JSON.stringify(value));
    const output = execFileSync(compilerCommand.executable, ['-cp', compilerCommand.classpath,
      'org.govpraya.builder.plan.PlanCli', file], {cwd: root, encoding: 'utf8', stdio: ['ignore', 'pipe', 'pipe']});
    return JSON.parse(output);
  } finally {
    fs.rmSync(directory, {recursive: true, force: true});
  }
}

function compileFails(compilerCommand, value) {
  try { compile(compilerCommand, value); return false; }
  catch { return true; }
}

test('the shipped part registry has the complete documented vocabulary', () => {
  const parts = readParts();
  assert.deepEqual(parts.map(part => part.id), expectedIds);
  assert.match(render(parts), /Generated by `preview\/generate-parts-docs\.cjs`/);
  for (const part of parts) {
    assert.equal(part.schema_version, 1);
    assert.ok(part.description && part.style && part.provenance.author && part.provenance.project);
    assert.ok(part.test && part.test.expect.valid === true);
    assert.ok(Object.keys(part.parameters).length > 0);
  }
});

test('each default part fixture compiles, remains caller-owned, and has no A1 errors', () => {
  const command = compiler();
  const warningProfile = {};
  for (const part of readParts()) {
    const candidate = compile(command, plan(part, part.test.params));
    assert.ok(candidate.blocks.length > 0, `${part.id} emitted no cells`);
    assert.ok(candidate.blocks.every(block => block.component === 'caller'), `${part.id} leaked part ownership`);
    const errors = diagnose(candidate, null, null).filter(entry => entry.severity === 'error');
    warningProfile[part.id] = diagnose(candidate, null, null).filter(entry => entry.severity === 'warning').map(entry => entry.rule);
    assert.deepEqual(errors, [], `${part.id} has A1 errors: ${JSON.stringify(errors)}`);
  }
  console.log(`A1 default warnings ${JSON.stringify(warningProfile)}`);
});

test('rotatable parts compile at all four quarter turns within their fixture dimensions', () => {
  const command = compiler();
  for (const part of readParts().filter(item => item.rotation)) {
    for (const facing of Object.keys(part.rotation.turns)) {
      const candidate = compile(command, plan(part, {...part.test.params, [part.rotation.param]: facing}, [20, 20, 20]));
      assert.ok(candidate.blocks.length > 0, `${part.id}/${facing} emitted no cells`);
      assert.ok(candidate.blocks.every(block => block.x >= 0 && block.x < 48 && block.y >= 0 && block.y < 64 && block.z >= 0 && block.z < 48), `${part.id}/${facing} escaped its fixture`);
    }
  }
});

test('part rotation changes directional block states with its geometry', () => {
  const command = compiler();
  const part = readParts().find(item => item.id === 'stair.straight');
  for (const facing of Object.keys(part.rotation.turns)) {
    const candidate = compile(command, plan(part, {...part.test.params, facing}, [20, 20, 20]));
    const stair = candidate.blocks.find(block => block.block.startsWith('minecraft:stone_brick_stairs['));
    assert.ok(stair, `missing stair for ${facing}`);
    assert.match(stair.block, new RegExp(`facing=${facing}`));
  }
});

test('integer parameter bounds reject values outside every declared range', () => {
  const command = compiler();
  for (const part of readParts()) {
    for (const [name, definition] of Object.entries(part.parameters)) {
      if (definition.type !== 'integer') continue;
      assert.equal(compileFails(command, plan(part, {[name]: definition.min - 1})), true, `${part.id}.${name} accepted below-minimum value`);
      assert.equal(compileFails(command, plan(part, {[name]: definition.max + 1})), true, `${part.id}.${name} accepted above-maximum value`);
    }
  }
});

function stairSite(candidate, frontage) {
  const blocks = [];
  for (let x = 0; x < candidate.dimensions.x; x++) for (let z = 0; z < candidate.dimensions.z; z++) {
    blocks.push({x, y: 4, z, block: 'minecraft:stone'});
  }
  return {origin: [0, 0, 0], dimensions: candidate.dimensions, frontage, blocks};
}

test('straight and switchback stairs carry an A1 walking route from lower to upper landing', () => {
  const command = compiler();
  const cases = [
    {id: 'stair.straight', frontage: [4, 5, 3], upperY: 9},
    {id: 'stair.switchback', frontage: [6, 5, 5], upperY: 9}
  ];
  for (const expected of cases) {
    const part = readParts().find(item => item.id === expected.id);
    const candidate = compile(command, plan(part, part.test.params));
    const access = analyzeAccess(stairSite(candidate, expected.frontage), candidate, {origin: [0, 0, 0], turns: 0});
    assert.ok(access.reachedPoints.some(point => point[1] >= expected.upperY), `${part.id} never reaches its upper landing`);
    assert.equal(access.headroom.filter(entry => entry.at[1] >= expected.upperY - 1).length, 0, `${part.id} blocks headroom at its upper landing`);
  }
});
