import {readTheme,saveTheme,bindThemeToggle} from '/review-state.js';
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let page=0,data,selected=null,editing=null,editVersion=0,view=null,imported=null,importVersion=0,ticket=0,sources={surveys:[],designs:[]},tracing=false,trace=[];
async function api(route='',body){const r=await fetch('/api/workspace/places'+route,body?{method:'POST',headers:{'Content-Type':'application/json','X-Builder-Write':'1'},body:JSON.stringify(body)}:{});const v=await r.json();if(!r.ok)throw Error(v.error);return v;}
function status(s){$('places-status').textContent=s;}
function options(id,values,label){const value=$(id).value;$(id).replaceChildren(new Option(label,''),...values.map(v=>new Option(id==='filter-world'?JSON.parse(v).filter(Boolean).join(' · '):v,v)));$(id).value=value;}
async function load(){const t=++ticket;try{const p=new URLSearchParams({page,q:$('find-place').value,kind:$('filter-kind').value,identity:$('filter-world').value,municipality:$('filter-municipality').value});const result=await api('?'+p);if(t!==ticket)return;data=result;options('filter-world',data.worlds,'All worlds');options('filter-municipality',data.municipalities,'All municipalities');$('place-list').innerHTML=data.items.length?data.items.map(r=>`<button class="place-card" data-id="${r.id}" aria-pressed="${selected===r.id}"><strong>${esc(r.name)}</strong><small>${esc(r.kind)} · ${esc(r.status)} · ${esc(r.verification)}</small><small>${esc([r.number,r.street,r.unit,r.municipality].filter(Boolean).join(' '))}</small></button>`).join(''):'<p>No places recorded here yet. Add an existing building, address or proposed parcel to begin.</p>';$('place-list').querySelectorAll('[data-id]').forEach(b=>b.onclick=()=>select(b.dataset.id));$('previous').disabled=page===0;$('next').disabled=page+1>=data.pages;$('page-label').textContent=`${page+1} / ${Math.max(1,data.pages)}`;status(`${data.total} records${data.mapTruncated?' · Map shows the first 500; narrow the filters.':''}`);draw();}catch(e){status(e.message);}}
function mapRecords(){const rows=data?.map||[],identities=new Set(rows.map(r=>r.world+'|'+r.worldId));return identities.size===1?rows:[];}
function draw(){const rows=mapRecords(),points=rows.flatMap(r=>r.boundary|| (r.position?[[r.position[0],r.position[2]]]:[]));if(!points.length&&!tracing){$('place-map').innerHTML='<text x="25" y="50" fill="#ccd5d7">'+(data?.map.length?'Select one world with mapped records.':'Add a boundary or position to map a place.')+'</text>';return;}
 if(!points.length&&!view)view={x:-50,z:-32.5,w:100,h:65};
 if(!view){const xs=points.map(p=>p[0]),zs=points.map(p=>p[1]);view={x:Math.min(...xs)-10,z:Math.min(...zs)-10,w:Math.max(40,Math.max(...xs)-Math.min(...xs)+20),h:Math.max(26,Math.max(...zs)-Math.min(...zs)+20)};if(view.w/view.h<800/520)view.w=view.h*800/520;else view.h=view.w*520/800;}
 const at=p=>[(p[0]-view.x)/view.w*800,(p[1]-view.z)/view.h*520];
 const step=10**Math.floor(Math.log10(view.w/8)),grid=[];for(let x=Math.ceil(view.x/step)*step;x<view.x+view.w;x+=step)grid.push(`<path d="M${at([x,view.z])[0]} 0V520"/>`);for(let z=Math.ceil(view.z/step)*step;z<view.z+view.h;z+=step)grid.push(`<path d="M0 ${at([view.x,z])[1]}H800"/>`);
 $('place-map').innerHTML=`<g stroke="#ffffff12">${grid.join('')}</g>`+rows.map(r=>{const color=r.kind==='parcel'?'#e7a16b':r.kind==='building'?'#7db9dd':'#8ecba0',title=`<title>${esc(r.name)} · ${esc(r.verification)}</title>`,attr=`data-id="${r.id}" tabindex="0" role="button" aria-label="${esc(r.name)}"`;return r.boundary?`<polygon ${attr} points="${r.boundary.map(p=>at(p).join(',')).join(' ')}" fill="${color}" fill-opacity="${selected===r.id?'.4':'.16'}" stroke="${color}" stroke-width="${selected===r.id?4:2}" stroke-dasharray="${r.verification==='verified'?'':'7 4'}">${title}</polygon>`:r.position?`<circle ${attr} cx="${at([r.position[0],r.position[2]])[0]}" cy="${at([r.position[0],r.position[2]])[1]}" r="7" fill="${color}">${title}</circle>`:'';}).join('')+`<text x="15" y="24" fill="#ccd5d7">X ${Math.round(view.x)}…${Math.round(view.x+view.w)} · Z ${Math.round(view.z)}…${Math.round(view.z+view.h)} · north ↑ (−Z)</text>`;
 if(tracing)$('place-map').innerHTML+=`<polyline points="${trace.map(p=>at(p).join(',')).join(' ')}" stroke="#fff" fill="none" stroke-width="3"/>`;
 $('place-map').querySelectorAll('[data-id]').forEach(el=>{el.onclick=()=>{if(!tracing)select(el.dataset.id);};el.onkeydown=e=>{if(e.key==='Enter'){select(el.dataset.id);}};});}
async function select(id){try{const d=await api('/'+id);selected=id;const r=d.record;$('place-detail').innerHTML=`<h2>${esc(r.name)}</h2><button id="edit-place">Edit record</button><dl><dt>Identity</dt><dd>${esc(r.kind)} · ${esc(r.status)} · ${esc(r.verification)}<br>${r.id}</dd><dt>World</dt><dd>${esc(r.world)} · ${esc(r.worldId||'ID unrecorded')}</dd><dt>Source</dt><dd>${esc(r.source||'Unrecorded')}</dd><dt>Related places</dt><dd>${d.related.map(v=>`<button data-related="${v.id}">${esc(v.name)}</button>`).join(' ')||'None'}</dd><dt>Surveys</dt><dd>${r.surveyEvidence.map(s=>`${esc(s.id)} · ${esc(s.capturedAt||'date unknown')} · ${esc(s.hash.slice(0,12))}`).join('<br>')||'None'}</dd><dt>Designs</dt><dd>${r.designs.map(id=>`<a href="/studio?draft=${id}">Open design ${id.slice(0,8)}</a>`).join('<br>')||'No generated design linked'}</dd></dl><details><summary>History (${d.history.length})</summary>${d.history.map(h=>`<details><summary>${esc(h.at)} · ${h.record?'version '+h.record.version+' · '+esc(h.record.source||'No source'):esc(h.lineage.type)}</summary><pre>${esc(JSON.stringify(h.record||h.lineage,null,2))}</pre></details>`).join('')}</details>`;$('edit-place').onclick=()=>editor(r,d.version);$('place-detail').querySelectorAll('[data-related]').forEach(b=>b.onclick=()=>select(b.dataset.related));draw();}catch(e){status(e.message);}}
function editor(record=null,version=data.version){editing=record;editVersion=version;const f=$('place-form');f.reset();for(const el of f.elements){if(!el.name)continue;if(el.multiple){const available=el.name==='surveys'?sources.surveys:sources.designs,list=[...available,...(record?.[el.name]||[]).filter(id=>!available.some(s=>s.id===id)).map(id=>({id,name:id}))];el.replaceChildren(...list.map(s=>new Option(s.name||s.id,s.id,false,(record?.[el.name]||[]).includes(s.id))));continue;}let v=record?.[el.name]??'';if(el.name==='boundary')v=(v||[]).map(p=>p.join(', ')).join('\n');else if(Array.isArray(v))v=v.join(', ');if(v!==''||el.tagName!=='SELECT')el.value=v;}$('editor-error').textContent='';$('editor-title').textContent=record?'Edit '+record.name:'Add place';f.elements.kind.disabled=Boolean(record);f.elements.world.readOnly=Boolean(record);f.elements.worldId.readOnly=Boolean(record);renderLinks();$('place-editor').showModal();}
function parseForm(){const f=$('place-form'),r={};for(const el of f.elements)if(el.name)r[el.name]=el.multiple?[...el.selectedOptions].map(o=>o.value):el.value.trim();for(const key of ['links'])r[key]=r[key]?r[key].split(',').map(s=>s.trim()):[];r.position=r.position?r.position.split(',').map(s=>Number(s.trim())):null;r.boundary=r.boundary?r.boundary.split('\n').filter(Boolean).map(line=>line.split(',').map(s=>Number(s.trim()))):null;if(editing)r.id=editing.id;return r;}
const mutate=async body=>{await api('',body);view=null;await load();};
$('place-form').onsubmit=async e=>{e.preventDefault();try{const r=parseForm();await mutate({expectedVersion:editVersion,records:[r]});$('place-editor').close();if(r.id)await select(r.id);}catch(e){$('editor-error').textContent=e.message;}};
$('new-place').onclick=()=>editor();$('close-editor').onclick=()=>$('place-editor').close();$('previous').onclick=()=>{page--;load();};$('next').onclick=()=>{page++;load();};for(const id of ['find-place','filter-kind','filter-world','filter-municipality'])$(id).addEventListener(id==='find-place'?'input':'change',()=>{page=0;view=null;load();});$('fit-map').onclick=()=>{view=null;draw();};
let drag;$('place-map').onpointerdown=e=>{if(tracing||e.target.closest('[data-id]')||!view)return;drag={x:e.clientX,z:e.clientY,view:{...view}};$('place-map').setPointerCapture(e.pointerId);};$('place-map').onpointermove=e=>{if(!drag)return;const rect=$('place-map').getBoundingClientRect();view={...drag.view,x:drag.view.x-(e.clientX-drag.x)/rect.width*drag.view.w,z:drag.view.z-(e.clientY-drag.z)/rect.height*drag.view.h};draw();};$('place-map').onpointerup=()=>drag=null;$('place-map').addEventListener('wheel',e=>{if(!view)return;e.preventDefault();const factor=e.deltaY>0?1.15:1/1.15;if(view.w*factor<4||view.w*factor>60000000)return;view={x:view.x+view.w*(1-factor)/2,z:view.z+view.h*(1-factor)/2,w:view.w*factor,h:view.h*factor};draw();},{passive:false});
$('import-open').onclick=()=>{$('import-editor').showModal();};$('import-close').onclick=()=>$('import-editor').close();$('import-json').oninput=()=>{imported=null;$('import-save').disabled=true;};$('import-review').onclick=async()=>{try{const raw=JSON.parse($('import-json').value),body=Array.isArray(raw)?{records:raw}:raw;const result=await api('/validate',body);imported=body;importVersion=result.version;$('import-preview').textContent=`${body.records.length} valid records reviewed. Sources: `+body.records.map(r=>r.source||'unverified / no source').join(' · ');$('import-save').disabled=false;}catch(e){$('import-preview').textContent=e.message;}};$('import-save').onclick=async()=>{try{await mutate({expectedVersion:importVersion,...imported});$('import-editor').close();}catch(e){$('import-preview').textContent=e.message;}};
async function loadSources(){sources=await api('/sources');$('source-survey').replaceChildren(new Option('Choose optional reference…',''),...sources.surveys.map(s=>new Option(s.name||s.id,s.id)));}
function renderLinks(){const ids=$('place-form').elements.links.value.split(',').map(s=>s.trim()).filter(Boolean);$('related-chips').replaceChildren(...ids.map(id=>{const b=document.createElement('button');b.type='button';b.textContent=id.slice(0,8)+' ×';b.onclick=()=>{$('place-form').elements.links.value=ids.filter(v=>v!==id).join(',');renderLinks();};api('/'+id).then(d=>b.textContent=d.record.name+' ×').catch(()=>{});return b;}));}
$('related-search').oninput=async()=>{const q=$('related-search').value,world=$('place-form').elements.world.value,identity=JSON.stringify([world,$('place-form').elements.worldId.value]);try{const result=await api('?'+new URLSearchParams({q,identity}));if(q!==$('related-search').value)return;$('related-results').replaceChildren(...result.items.filter(r=>r.id!==editing?.id).map(r=>{const b=document.createElement('button');b.type='button';b.textContent=r.name+' · '+r.kind;b.onclick=()=>{const f=$('place-form').elements.links,ids=f.value.split(',').map(s=>s.trim()).filter(Boolean);if(!ids.includes(r.id))ids.push(r.id);f.value=ids.join(',');renderLinks();};return b;}));}catch(e){$('editor-error').textContent=e.message;}};
$('source-survey').onchange=()=>{const s=sources.surveys.find(s=>s.id===$('source-survey').value),f=$('place-form').elements;if(!s)return;if(!editing){f.world.value=s.world;f.worldId.value=s.worldId;f.position.value=s.origin.join(', ');}for(const o of f.surveys.options)if(o.value===s.id)o.selected=true;};
$('trace-boundary').onclick=()=>{tracing=true;trace=[];$('place-editor').close();$('trace-tools').hidden=false;const position=$('place-form').elements.position.value.split(',').map(Number);view=position.length===3&&position.every(Number.isFinite)?{x:position[0]-50,z:position[2]-32.5,w:100,h:65}:null;draw();$('place-map').scrollIntoView({block:'center'});};
$('place-map').addEventListener('click',e=>{if(!tracing||!view)return;const p=$('place-map').createSVGPoint();p.x=e.clientX;p.y=e.clientY;const local=p.matrixTransform($('place-map').getScreenCTM().inverse());trace.push([Math.round(view.x+local.x/800*view.w),Math.round(view.z+local.y/520*view.h)]);draw();});
function endTrace(save){if(save&&trace.length<3){status('Choose at least three corners.');return;}if(save)$('place-form').elements.boundary.value=trace.map(p=>p.join(', ')).join('\n');tracing=false;$('trace-tools').hidden=true;draw();$('place-editor').showModal();}
$('trace-finish').onclick=()=>endTrace(true);$('trace-cancel').onclick=()=>endTrace(false);
Promise.all([load(),loadSources()]).catch(e=>status(e.message));

const theme=readTheme()||'light';document.documentElement.dataset.theme=theme;bindThemeToggle($("theme-toggle"),theme,t=>{document.documentElement.dataset.theme=t;saveTheme(t);});
