import {readTheme,saveTheme,bindThemeToggle} from '/review-state.js';
import {esc,isAir,normalizeBlocks,drawPlan,drawProfile,drawSection,drawModel,fitModel} from '/roadwork-view.js';

const api='/api/roadwork';
const variants={
  terrain:{name:'Terrain fit',note:'Ranks seven nearby routes by review issues, earthwork, disturbance and length. Fixed end tie-ins.'},
  preserve:{name:'Follow points',note:'Follows the supplied control points.'},
  balanced:{name:'Modest bend',note:'Applies a modest bend offset to the control point path.'},
  direct:{name:'Straighten',note:'Moves intermediate points toward the line between the tie-ins.'}
};
const $=selector=>document.querySelector(selector);
const $$=selector=>[...document.querySelectorAll(selector)];
const state={context:null,survey:null,surveyId:null,surveyRecord:null,blocks:[],suggestedPoints:[],points:[],width:7,section:'provisional',alternative:'balanced',assemblies:{},saved:null,station:50,view:'plan',showSurvey:true,showChanges:true,showGrid:false,busy:false,dirty:false,generation:0,compileQueued:false};
const theme=readTheme()||'dark';
document.documentElement.dataset.theme=theme;
bindThemeToggle($('#theme-toggle'),theme,next=>{document.documentElement.dataset.theme=next;saveTheme(next);});

async function request(path,options={}) {
  const response=await fetch(api+path,{...options,headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json','X-Builder-Write':'1'}:{}),...(options.headers||{})}});
  const contentType=response.headers.get('content-type')||'';
  const data=contentType.includes('json')?await response.json():await response.text();
  if(!response.ok)throw new Error(typeof data==='object'?(data.error?.message||data.error||data.message||'Request failed'):data||'Request failed');
  return data;
}
function error(message){const box=$('#app-error');box.textContent=message;box.hidden=false;clearTimeout(error.timer);error.timer=setTimeout(()=>box.hidden=true,12000);}
function toast(message){const box=$('#toast');box.textContent=message;box.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>box.hidden=true,3000);}
function panel(name){$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);$$('[data-workflow]').forEach(b=>{if(b.dataset.workflow===name)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});window.scrollTo(0,0);}
function setSaveState(message,status='idle'){$('#save-state').dataset.state=status;$('#save-state').innerHTML='<i></i> '+esc(message);}
function setBusy(busy,message){state.busy=busy;$('#compile-study').disabled=busy||!state.survey;$('#load-survey').disabled=busy;$('#survey-select').disabled=busy;$('#save-study').disabled=busy||!state.assemblies[state.alternative]||state.saved&&!state.dirty;for(const input of $$('#point-list input,#road-width,#add-point,#remove-point,#reset-study,.alternative-card'))input.disabled=busy;$('#compile-state').textContent=message;}
function setDirty(){state.generation++;state.dirty=true;state.saved=null;state.assemblies={};if(state.busy)state.compileQueued=true;setSaveState('Changes need generation','unsaved');renderAlternatives();renderReview();renderDrawing();clearTimeout(setDirty.timer);setDirty.timer=setTimeout(()=>compileAll(),550);}
function selectedSurveyId(){return $('#survey-select').value;}
function surveyIdentity(){const s=state.surveyRecord||state.survey||{};return {id:state.surveyId??s.id??selectedSurveyId(),name:s.name??'Survey',world:s.world??s.worldName??'Unknown world',worldId:s.worldId??s.worldUuid??'unidentified',origin:s.origin??{x:0,y:0,z:0},dimensions:s.dimensions??{x:0,y:0,z:0},capturedAt:s.capturedAt??s.createdAt??null,source:s.source??null};}
function isFixture(){return state.surveyId==='fixture'||String(surveyIdentity().source).includes('fixture');}
function date(value){if(!value)return 'capture date unavailable';const d=new Date(value);return Number.isNaN(d.getTime())?String(value):d.toLocaleString();}
function safeNumber(value,fallback=0){const n=Number(value);return Number.isFinite(n)?n:fallback;}
function axis(point,key){return safeNumber(Array.isArray(point)?point[{x:0,y:1,z:2}[key]]:point?.[key]);}
function normalizePoint(p){if(Array.isArray(p))return {x:Math.round(safeNumber(p[0])),y:Math.round(safeNumber(p[1])),z:Math.round(safeNumber(p[2]))};return {x:Math.round(safeNumber(p?.x)),y:Math.round(safeNumber(p?.y)),z:Math.round(safeNumber(p?.z))};}
function defaultPoints(){const s=surveyIdentity(),o=s.origin,d=s.dimensions;const ox=axis(o,'x'),oy=axis(o,'y'),oz=axis(o,'z'),dx=safeNumber(d.x,32),dz=safeNumber(d.z,32);const first={x:ox+Math.max(4,Math.floor(dx*.20)),z:oz+Math.max(4,Math.floor(dz*.25))},last={x:ox+Math.min(dx-5,Math.floor(dx*.78)),z:oz+Math.min(dz-5,Math.floor(dz*.72))};for(const p of [first,last]){const nearby=state.blocks.filter(b=>Math.abs(b.x-p.x)<=2&&Math.abs(b.z-p.z)<=2&&!isAir(b.state));p.y=nearby.length?Math.max(...nearby.map(b=>b.y)):axis(o,'y')+Math.floor(safeNumber(d.y,16)/2);}return [first,last];}

async function loadContext(){try{const context=await request('/context');state.context=context;const surveys=context.surveys||[];const fixture=context.fixtureAvailable&&!surveys.some(s=>s.id==='fixture')?[{id:'fixture',name:'Two-segment test fixture',world:'Synthetic test fixture',source:'fixture'}]:[];const all=[...surveys,...fixture];$('#survey-select').innerHTML=all.length?all.map(s=>'<option value="'+esc(s.id)+'">'+esc(s.name||s.id)+' · '+esc(s.world||'unknown world')+(s.id==='fixture'?' · TEST FIXTURE':'')+'</option>').join(''):'<option value="">No surveys available</option>';const real=all.find(s=>s.id!=='fixture'&&String(s.world||'').includes('test'))||all.find(s=>s.id!=='fixture')||all[0];if(real)$('#survey-select').value=real.id;updateSurveyChoice();renderStudyList(context.studies||[]);const linked=new URLSearchParams(location.search).get('study');if(linked){await openStudy(linked);return;}if(real&&real.id!=='fixture')await openSurvey(real.id);else setSaveState('Choose a survey','idle');}catch(e){error('Roadwork service unavailable: '+e.message);$('#survey-select').innerHTML='<option value="">Unable to load surveys</option>';setSaveState('Connection unavailable','unsaved');}}
function updateSurveyChoice(){const entry=(state.context?.surveys||[]).find(s=>s.id===selectedSurveyId());$('#survey-description').textContent=selectedSurveyId()==='fixture'?'Synthetic TEST FIXTURE. Use this to exercise two segments; it is not a Praya road survey.':entry?'World '+(entry.world||'unknown')+' · '+date(entry.capturedAt)+' · '+(entry.dimensions?Object.values(entry.dimensions).join(' × ')+' blocks':'dimensions unavailable'):'Select a survey to inspect.';}
function renderStudyList(studies){$('#study-list').innerHTML=studies.length?studies.map(s=>'<button type="button" class="saved-study" data-study="'+esc(s.id)+'"><strong>'+esc(s.name||'Untitled road study')+'</strong><small>'+esc(date(s.createdAt))+' · '+esc(String(s.hash||'').slice(0,10))+'</small></button>').join(''):'<p>No saved road studies yet.</p>';$$('.saved-study').forEach(b=>b.addEventListener('click',()=>openStudy(b.dataset.study)));}
async function openSurvey(id){if(!id||state.busy)return;state.generation++;setBusy(true,'Loading surveyed Minecraft blocks…');try{const payload=await request('/surveys/'+encodeURIComponent(id));state.survey=payload.survey||payload.site||payload;state.surveyId=id;state.surveyRecord=(state.context?.surveys||[]).find(s=>s.id===id)||state.survey;state.blocks=normalizeBlocks(state.survey);state.suggestedPoints=(payload.suggestedPoints||[]).map(normalizePoint);state.points=state.suggestedPoints.length>=2?state.suggestedPoints.map(p=>({...p})):defaultPoints();state.section='provisional';$('#road-section').value=state.section;$('#road-width').disabled=false;state.width=7;state.alternative='balanced';state.assemblies={};state.saved=null;state.station=50;state.dirty=true;$('#road-width').value=state.width;renderPointInputs();renderSource(payload.detection);render();panel('design');setSaveState('Survey loaded · design unsaved','unsaved');setBusy(false,'Survey loaded. Generating measured alternatives…');await compileAll();}catch(e){error('Could not open survey: '+e.message);setBusy(false,'Survey failed to load.');}}
function renderSource(detection){const s=surveyIdentity(),fixture=isFixture();$('#source-badge').textContent=fixture?'TEST FIXTURE':'MINECRAFT SURVEY';$('#source-description').textContent=(fixture?'Synthetic example':'Read-only survey')+' · '+s.name+' · '+s.world+' · '+date(s.capturedAt);$('#source-boundary').textContent='NO WORLD CHANGES';$('#study-file').textContent=fixture?'ROAD STUDY / SYNTHETIC TEST FIXTURE':'ROAD STUDY / SURVEY '+String(s.id).slice(0,8);$('#study-title').textContent=s.name||'Untitled corridor';$('#study-subtitle').textContent=fixture?'Illustrative terrain for compiler verification · no Praya location':'Minecraft block survey · '+state.blocks.length.toLocaleString()+' captured block records';const facts=$('#survey-facts');facts.hidden=false;facts.innerHTML='<div><strong>World</strong><span>'+esc(s.world)+'</span></div><div><strong>Origin</strong><span>'+esc([axis(s.origin,'x'),axis(s.origin,'y'),axis(s.origin,'z')].join(', '))+'</span></div><div><strong>Dimensions</strong><span>'+esc(Object.values(s.dimensions).join(' × '))+'</span></div><div><strong>Route basis</strong><span>'+esc(detection?.confidence==='road'?'Detected road trace':'Suggested alignment · road trace unverified')+'</span></div>';}
function renderPointInputs(){const parent=$('#point-list');parent.innerHTML=state.points.map((p,i)=>'<fieldset class="point-row"><legend>'+(i===0?'Start tie-in':i===state.points.length-1?'End tie-in':'Waypoint '+i)+'</legend>'+['x','y','z'].map(axis=>'<label>'+axis.toUpperCase()+'<input type="number" step="1" data-point="'+i+'" data-axis="'+axis+'" value="'+esc(p[axis])+'" aria-label="'+axis.toUpperCase()+' for point '+(i+1)+'"></label>').join('')+'</fieldset>').join('');parent.querySelectorAll('input').forEach(input=>input.addEventListener('change',()=>{const n=Number(input.value);if(!Number.isInteger(n)){error('World coordinates must be whole blocks.');input.value=state.points[Number(input.dataset.point)][input.dataset.axis];return;}state.points[Number(input.dataset.point)][input.dataset.axis]=n;setDirty();renderDrawing();}));$('#remove-point').disabled=state.points.length<=2;$('#add-point').disabled=state.points.length>=8;}
function assembly(key=state.alternative){return state.assemblies[key]||null;}
function metric(a,key,fallback='—'){const m=a?.metrics||{};const v=m[key];return v==null?fallback:v;}
function length(a){const m=a?.metrics||{};return m.length??m.routeLength??m.lengthBlocks??a?.samples?.at(-1)?.distance??'—';}
function grade(a){const m=a?.metrics||{};if(m.maxStepGrade!=null)return Math.round(m.maxStepGrade*100)+'% voxel step';if(m.maxGradePercent!=null)return m.maxGradePercent;if(m.maxGrade!=null)return m.maxGrade;const points=a?.points||[];let maximum=0;for(let i=1;i<points.length;i++){const p=points[i-1],q=points[i],run=Math.hypot(q.x-p.x,q.z-p.z);if(run)maximum=Math.max(maximum,Math.abs(q.y-p.y)/run*100);}return points.length>1?maximum.toFixed(1)+'%':'—';}
function changeCount(a){return a?.changes?.length??a?.metrics?.changedBlocks??0;}
function renderAlternatives(){const ranked=Object.keys(variants).filter(k=>assembly(k)).sort((x,y)=>(assembly(x).metrics.terrainCost??Infinity)-(assembly(y).metrics.terrainCost??Infinity));$('#alternative-list').innerHTML=Object.entries(variants).map(([key,v])=>{const a=assembly(key),issues=a?.issues?.length??0;return '<button type="button" class="alternative-card" role="radio" data-alternative="'+key+'" aria-checked="'+(state.alternative===key)+'" '+(state.busy?'disabled':'')+'><span class="alt-top"><strong>'+esc(v.name)+'</strong><span class="recommendation">'+(a?('#'+(ranked.indexOf(key)+1)+' · '+(a.ready?'BLOCK ARTIFACT':'REVIEW ISSUES')):'PENDING')+'</span></span><p>'+esc(v.note)+'</p><dl><div><dt>Length</dt><dd>'+esc(length(a))+' blocks</dd></div><div><dt>Terrain cost</dt><dd>'+esc(a?Math.round(a.metrics.terrainCost??0):'—')+'</dd></div><div><dt>Changes</dt><dd>'+esc(a?changeCount(a):'—')+'</dd></div><div><dt>Issues</dt><dd>'+esc(a?issues:'—')+'</dd></div></dl></button>';}).join('');$$('.alternative-card').forEach(card=>card.addEventListener('click',()=>{if(state.busy||state.alternative===card.dataset.alternative)return;state.alternative=card.dataset.alternative;if(state.saved?.assembly?.hash!==assembly()?.hash){state.saved=null;state.dirty=true;setSaveState('Alternative selected · save this revision','unsaved');}render();}));}
function renderDrawing(){if(!state.survey)return;const args={survey:state.survey,blocks:state.blocks,assembly:assembly(),points:state.points,station:state.station,showSurvey:state.showSurvey,showChanges:state.showChanges,showGrid:state.showGrid};drawPlan($('#plan-view'),args);drawProfile($('#profile-view'),args);drawSection($('#section-view'),args);$('#plan-view').toggleAttribute('hidden',state.view!=='plan');$('#model-view').hidden=state.view!=='model';if(state.view==='model')drawModel($('#model-view'),args);const a=assembly(),distance=length(a);const at=typeof distance==='number'?Math.round(distance*state.station/100):'—';$('#station-output').textContent=at+' / '+distance+' blocks';$('#section-station').textContent='At '+at+' blocks';$$('[data-view]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.view===state.view)));$('#plan-view').querySelectorAll('[data-point]').forEach(node=>{const index=Number(node.dataset.point);node.addEventListener('click',()=>{document.querySelector('[data-point="'+index+'"][data-axis="x"]')?.focus();});node.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();document.querySelector('[data-point="'+index+'"][data-axis="x"]')?.focus();}});});}
function portText(port){return port?.at?'('+port.at.join(', ')+')'+(port.endpoint?' · tie-in':' · shared seam'):'—';}
function renderReview(){const a=assembly();$('#review-table').innerHTML=Object.entries(variants).map(([key,v])=>{const item=assembly(key);return '<tr data-selected="'+(key===state.alternative)+'"><td><strong>'+esc(v.name)+'</strong></td><td>'+esc(length(item))+'</td><td>'+esc(grade(item))+'</td><td>'+esc(item?changeCount(item):'—')+'</td><td>'+esc(item?.segments?.length??'—')+'</td><td>'+esc(item?.issues?.length??'—')+'</td></tr>';}).join('');$('#review-choice').textContent=variants[state.alternative].name;$('#review-intro').textContent=a?'Exact changes from '+surveyIdentity().name+' · '+(isFixture()?'synthetic test fixture':'Minecraft survey'):'Generate a route to review exact block changes.';$('#review-summary').textContent=a?'Assembly '+String(a.hash||'unhashed').slice(0,16)+' · '+(a.ready?'review checks passed':'review issues need attention'):'No current generated artifact.';$('#review-details').innerHTML=a?'<dt>Section</dt><dd>'+esc(a.sectionNote||'Legacy provisional section')+'</dd><dt>Ranking</dt><dd>'+esc(a.metrics.costBasis||'Unranked legacy study')+'</dd><dt>Survey hash</dt><dd class="hash">'+esc(String(a.surveyHash||'missing').slice(0,16))+'</dd><dt>Route length</dt><dd>'+esc(length(a))+' blocks</dd><dt>Maximum grade</dt><dd>'+esc(grade(a))+'</dd><dt>Block changes</dt><dd>'+changeCount(a).toLocaleString()+'</dd><dt>Segments</dt><dd>'+esc(a.segments?.length??0)+'</dd>':'';const issues=a?.issues||[];$('#review-caution').innerHTML=a?'<strong>'+(a.ready?'Generated artifact · placement separate':issues.length+' review issue'+(issues.length===1?'':'s'))+'</strong><p>'+esc(issues.length?issues.map(i=>typeof i==='string'?i:i.message||i.code||'Issue').slice(0,4).join(' · '):'Exact schematics and manifest can be exported after saving this revision. No world changes occur here.')+'</p>':'<strong>Awaiting compilation</strong><p>A surveyed block artifact is needed before export.</p>';$('#segment-list').innerHTML=a?.segments?.length?'<h3>Bounded segments</h3>'+a.segments.map((s,i)=>'<article><strong>'+esc(s.id||'Segment '+(i+1))+'</strong><span>Origin '+esc(Array.isArray(s.origin)?s.origin.join(', '):[s.origin?.x,s.origin?.y,s.origin?.z].join(', '))+'</span><span>'+esc(s.artifact?.blocks?.length??0)+' blocks</span><small>Entry '+esc(portText(s.ports?.entry))+' · Exit '+esc(portText(s.ports?.exit))+' · artifact '+esc(s.artifact?.hash||'')+'</small></article>').join(''):'<p class="muted">No segments generated.</p>';$('#change-list').innerHTML=a?.changes?.length?'<h3>Block changes <small>first 40 of '+a.changes.length+'</small></h3><div class="change-rows">'+a.changes.slice(0,40).map(c=>'<div><code>'+esc([c.x,c.y,c.z].join(', '))+'</code><span>'+esc(c.before??'unknown')+' → '+esc(c.after??'air')+'</span><b>'+esc(c.classification||c.component||'change')+'</b></div>').join('')+'</div>':'';$('#export-manifest').disabled=!state.saved||state.dirty||!a;$('#download-segments').disabled=!state.saved||state.dirty||!a?.segments?.length;}
function render(){renderAlternatives();renderDrawing();renderReview();$('#save-study').disabled=state.busy||!assembly()||state.saved&&!state.dirty;if(!assembly()?.ready)$('#download-segments').disabled=true;}

async function compileAll(){if(!state.survey)return;if(state.busy){state.compileQueued=true;return;}const generation=++state.generation;state.compileQueued=false;setBusy(true,'Generating exact blocks for four alternatives…');const input={surveyId:state.surveyId,points:state.points.map(p=>({...p})),width:state.width,section:state.section};let success=0;for(const key of Object.keys(variants)){if(generation!==state.generation)break;try{const a=await request('/compile',{method:'POST',body:JSON.stringify({...input,alternative:key})});if(generation!==state.generation)break;state.assemblies[key]=a;success++;render();$('#compile-state').textContent='Generated '+success+' of 4 alternatives…';}catch(e){if(generation!==state.generation)break;state.assemblies[key]=null;error(variants[key].name+': '+e.message);}}setBusy(false,generation===state.generation&&success?success+' measured alternatives · '+(assembly()?.issues?.length||0)+' issues in selected option':'Awaiting current route generation.');render();if(generation!==state.generation||state.compileQueued){state.compileQueued=false;compileAll();}}
async function save(){if(state.busy)return;const a=assembly();if(!a){error('Generate a block artifact before saving.');return;}const generation=state.generation,selectedAlternative=state.alternative;setBusy(true,'Saving immutable road study…');try{const defaultName=surveyIdentity().name+' · '+variants[state.alternative].name;const payload=await request('/studies',{method:'POST',body:JSON.stringify({name:defaultName,surveyId:state.surveyId,points:state.points,width:state.width,section:state.section,alternative:state.alternative,hash:a.hash})});if(generation!==state.generation||selectedAlternative!==state.alternative||a.hash!==assembly()?.hash){toast('A previous revision was saved. Generate the current route again.');return;}state.saved=payload;state.dirty=false;setSaveState('Saved revision '+String(payload.id||'').slice(0,8),'saved');toast('Road study saved with pinned artifact hash.');const context=await request('/context');state.context=context;renderStudyList(context.studies||[]);render();}catch(e){error('Could not save study: '+e.message);}finally{setBusy(false,assembly()?'Exact blocks generated.':'No current artifact.');render();}}
async function openStudy(id){if(state.busy)return;state.generation++;setBusy(true,'Opening saved road study…');try{const payload=await request('/studies/'+encodeURIComponent(id));const input=payload.input||payload;state.survey=payload.survey;state.surveyId=input.surveyId||payload.survey?.id||null;state.surveyRecord=payload.survey;state.blocks=normalizeBlocks(state.survey);state.points=(input.points||payload.assembly?.points||[]).map(normalizePoint);state.suggestedPoints=state.points.map(p=>({...p}));state.section=input.section||'provisional';$('#road-section').value=state.section;$('#road-width').disabled=state.section==='compact-slab';state.width=Number(input.width||7);state.alternative=input.alternative||'balanced';state.assemblies={[state.alternative]:payload.assembly};state.saved=payload;state.dirty=false;state.station=50;$('#survey-select').value=state.surveyId||'';$('#road-width').value=state.width;renderPointInputs();renderSource();setSaveState('Saved revision '+String(id).slice(0,8),'saved');render();panel('review');toast('Saved study reopened.');}catch(e){error('Could not reopen study: '+e.message);}finally{setBusy(false,assembly()?'Saved block artifact loaded.':'No artifact loaded.');render();}}
async function exportManifest(){if(!state.saved||state.dirty){error('Save the current generated revision before export.');return;}window.location.assign(api+'/studies/'+encodeURIComponent(state.saved.id)+'/manifest');}
async function exportSegments(){const a=assembly();if(!state.saved||state.dirty||!a)return;if(!a.ready){error('Resolve road review issues before schematic export.');return;}for(const segment of a.segments||[]){const link=document.createElement('a');link.href=api+'/studies/'+encodeURIComponent(state.saved.id)+'/segments/'+encodeURIComponent(segment.id)+'.schem?hash='+encodeURIComponent(a.hash);link.download=segment.id+'.schem';document.body.append(link);link.click();link.remove();await new Promise(resolve=>setTimeout(resolve,200));}toast((a.segments||[]).length+' schematic download'+(a.segments?.length===1?'':'s')+' started.');}

$$('[data-workflow]').forEach(b=>b.addEventListener('click',()=>panel(b.dataset.workflow)));
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;renderDrawing();}));
$('#survey-select').addEventListener('change',updateSurveyChoice);
$('#load-survey').addEventListener('click',()=>openSurvey(selectedSurveyId()));
$('#reset-study').addEventListener('click',()=>{state.points=state.suggestedPoints.length>=2?state.suggestedPoints.map(p=>({...p})):defaultPoints();state.width=state.section==='compact-slab'?4:7;$('#road-width').value=state.width;renderPointInputs();setDirty();renderDrawing();});
$('#add-point').addEventListener('click',()=>{const a=state.points.at(-2),b=state.points.at(-1);state.points.splice(-1,0,{x:Math.round((a.x+b.x)/2),y:Math.round((a.y+b.y)/2),z:Math.round((a.z+b.z)/2)});renderPointInputs();setDirty();renderDrawing();});
$('#remove-point').addEventListener('click',()=>{if(state.points.length<=2)return;state.points.splice(-2,1);renderPointInputs();setDirty();renderDrawing();});
$('#road-section').addEventListener('change',e=>{state.section=e.target.value;state.width=state.section==='compact-slab'?4:7;$('#road-width').value=state.width;$('#road-width').disabled=state.section==='compact-slab';setDirty();});
$('#road-width').addEventListener('change',e=>{const n=Number(e.target.value);if(!Number.isInteger(n)||n<3||n>15||n%2!==1){error('Road width must be an odd number from 3 to 15 blocks.');e.target.value=state.width;return;}state.width=n;setDirty();});
$('#station').addEventListener('input',e=>{state.station=Number(e.target.value);renderDrawing();});
$('#show-survey').addEventListener('change',e=>{state.showSurvey=e.target.checked;renderDrawing();});
$('#show-changes').addEventListener('change',e=>{state.showChanges=e.target.checked;renderDrawing();});
$('#show-grid').addEventListener('change',e=>{state.showGrid=e.target.checked;renderDrawing();});
$('#compile-study').addEventListener('click',()=>compileAll());
$('#save-study').addEventListener('click',save);
$('#export-manifest').addEventListener('click',exportManifest);
$('#download-segments').addEventListener('click',exportSegments);
$('#fit-route').addEventListener('click',()=>{state.station=50;$('#station').value=50;fitModel();renderDrawing();});
$('#jump-end').addEventListener('click',()=>{state.station=100;$('#station').value=100;renderDrawing();});
$('#back-to-design').addEventListener('click',()=>panel('design'));
loadContext();
