import {readTheme,saveTheme,bindThemeToggle} from '/review-state.js';
const KEY='pbd.transport.study.v1';
const alternatives={
 preserve:{name:'Preserve approach',note:'Keeps the existing bend and limits terrain reshaping.',points:[[85,410],[225,390],[360,312],[515,226],[690,174],[835,166],[935,166]],intervention:'Lower',grade:4.8},
 balanced:{name:'Balanced curve',note:'Broadens the bend while sharing cut and fill.',points:[[85,410],[230,372],[390,286],[550,212],[700,172],[835,166],[935,166]],intervention:'Moderate',grade:3.9,recommended:true},
 direct:{name:'Direct approach',note:'Shorter line with visibly greater terrain intervention.',points:[[85,410],[255,338],[440,247],[610,189],[735,168],[835,166],[935,166]],intervention:'Higher',grade:4.3}
};
const summaries={preserve:'Retains the strongest trace of the existing curve. It asks less of the terrain, but leaves the longest and least direct approach.',balanced:'Uses a broader curve and an earlier bridge tangent. It is the clearest compromise in this synthetic comparison.',direct:'Makes the approach shorter and straighter. The line cuts farther into the uphill side and needs more terrain intervention.'};
const state={alternative:'balanced',station:46,curve:0,elevation:0,lane:4,median:3,shoulder:2,terrain:'solid',existing:true,proposed:true,earthworks:true,stepping:false,view:'plan'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const initialTheme=readTheme()||'dark';document.documentElement.dataset.theme=initialTheme;bindThemeToggle($('#theme-toggle'),initialTheme,t=>{document.documentElement.dataset.theme=t;saveTheme(t);});
function spline(points,n=160){const out=[];for(let i=0;i<points.length-1;i++){const p0=points[Math.max(0,i-1)],p1=points[i],p2=points[i+1],p3=points[Math.min(points.length-1,i+2)],count=Math.max(2,Math.round(n/(points.length-1)));for(let j=0;j<count;j++){const t=j/count,t2=t*t,t3=t2*t;out.push([.5*(2*p1[0]+(-p0[0]+p2[0])*t+(2*p0[0]-5*p1[0]+4*p2[0]-p3[0])*t2+(-p0[0]+3*p1[0]-3*p2[0]+p3[0])*t3),.5*(2*p1[1]+(-p0[1]+p2[1])*t+(2*p0[1]-5*p1[1]+4*p2[1]-p3[1])*t2+(-p0[1]+3*p1[1]-3*p2[1]+p3[1])*t3)]);}}out.push(points.at(-1));return out;}
function points(key=state.alternative){const pts=alternatives[key].points.map(p=>[...p]);for(let i=1;i<pts.length-3;i++)pts[i][1]+=state.curve*Math.sin(i/(pts.length-3)*Math.PI);return pts;}
function route(key=state.alternative){const raw=spline(key===state.alternative?points(key):alternatives[key].points),dist=[0];let length=0;for(let i=1;i<raw.length;i++){length+=Math.hypot(raw[i][0]-raw[i-1][0],raw[i][1]-raw[i-1][1]);dist.push(length);}return{raw,dist,length};}
function position(data,pct=state.station){const target=data.length*pct/100;let i=data.dist.findIndex(d=>d>=target);if(i<1)i=1;const span=data.dist[i]-data.dist[i-1]||1,t=(target-data.dist[i-1])/span,a=data.raw[i-1],b=data.raw[i];return{x:a[0]+(b[0]-a[0])*t,y:a[1]+(b[1]-a[1])*t,angle:Math.atan2(b[1]-a[1],b[0]-a[0]),distance:target};}
const roadWidth=()=>state.lane*4+state.median+state.shoulder*2;
function metrics(key=state.alternative){const r=route(key);return{length:Math.round(r.length*.23),grade:(alternatives[key].grade+(key===state.alternative?Math.abs(state.elevation)*.12:0)).toFixed(1),width:roadWidth()};}
const d=pts=>'M'+pts.map(p=>`${p[0].toFixed(1)} ${p[1].toFixed(1)}`).join(' L');
function renderAlternatives(){$('#alternative-list').innerHTML=Object.entries(alternatives).map(([key,a])=>{const m=metrics(key);return `<button class="alternative-card" role="radio" data-alternative="${key}" aria-checked="${key===state.alternative}"><span class="alt-top"><strong>${a.name}</strong>${a.recommended?'<span class="recommendation">RECOMMENDED</span>':''}</span><p>${a.note}</p><dl><div><dt>Length</dt><dd>${m.length} m</dd></div><div><dt>Max grade</dt><dd>${m.grade}%</dd></div><div><dt>Intervention</dt><dd>${a.intervention}</dd></div></dl></button>`;}).join('');$$('.alternative-card').forEach(b=>b.onclick=()=>{state.alternative=b.dataset.alternative;state.curve=0;$('#curve-offset').value=0;dirty();render();});}
function contours(){let out='';for(let i=0;i<14;i++){const y=38+i*34;let path=`M0 ${y}`;for(let x=0;x<=1000;x+=35)path+=` L${x} ${y+Math.sin(x/105+i*.7)*13+(x/1000)*16}`;out+=`<path class="plan-contour" d="${path}"/>`;}return out;}
function drawPlan(){const svg=$('#plan-view'),r=route(),path=d(r.raw),pos=position(r),nx=-Math.sin(pos.angle),ny=Math.cos(pos.angle),half=roadWidth()*1.15,cross=[pos.x-nx*half,pos.y-ny*half,pos.x+nx*half,pos.y+ny*half],pave=roadWidth()*2.12,median=Math.max(3,state.median*1.7);const defs='<defs><pattern id="warningPattern" width="12" height="12" patternUnits="userSpaceOnUse" patternTransform="rotate(45)"><rect width="6" height="12" fill="#f1c933"/><rect x="6" width="6" height="12" fill="#20211f"/></pattern></defs>';const terrain=state.terrain==='hidden'?'':`<rect class="terrain-fill" width="1000" height="520" opacity="${state.terrain==='cutaway'?'.45':'1'}"/>${contours()}<path class="water-fill" d="M865 0C835 100 891 185 866 285C843 378 900 440 890 520H1000V0Z"/>`;const works=state.earthworks?`<path class="earthwork-cut" d="${path}" stroke-width="${pave+39}"/><path class="earthwork-fill" d="${path}" stroke-width="${pave+22}"/>`:'';const proposed=state.proposed?`${works}<path class="road-shadow" d="${path}" stroke-width="${pave+7}"/><path class="road-pavement" d="${path}" stroke-width="${pave}"/><path class="road-edge" d="${path}" stroke-width="${pave-4}"/><path class="road-pavement" d="${path}" stroke-width="${pave-9}"/><path class="road-median" d="${path}" stroke-width="${median}"/><path class="center-line" d="${path}" stroke-width="2"/>`:'';svg.innerHTML=`${defs}${terrain}${state.existing?`<path class="existing-line" d="${d(spline(alternatives.preserve.points))}" stroke-width="3"/>`:''}${proposed}<path d="M919 122h16v19h-16zM919 191h16v19h-16z" class="warning-face"/><path class="station-mark" d="M${cross.join(' ')}"/><circle class="station-dot" cx="${pos.x}" cy="${pos.y}" r="7"/><text class="plan-label" x="842" y="139">LOCKED BRIDGE TANGENT</text><text class="plan-note" x="842" y="153">barrier-end warnings</text><text class="plan-label" x="80" y="451">EXISTING CONNECTION</text><text class="plan-note" x="80" y="466">provisional local origin</text>`;}
function drawProfile(){const svg=$('#profile-view'),left=35,top=17,w=720,h=190,iw=670,ih=145,n=80,terrain=[],road=[];for(let i=0;i<n;i++){const t=i/(n-1),x=left+t*iw,ty=62+12*Math.sin(t*7.2)+37*t+7*Math.sin(t*2.1),ry=68+29*t+state.elevation*3.2+Math.sin(t*Math.PI)*2;terrain.push([x,top+(110-ty)/70*ih]);road.push([x,top+(110-ry)/70*ih]);}let grid='';for(let i=0;i<=4;i++){const y=top+i*ih/4;grid+=`<path class="profile-grid" d="M${left} ${y}H705"/>`;}const x=left+state.station/100*iw,index=Math.round(state.station/100*(n-1));svg.innerHTML=`${grid}<path class="profile-terrain" d="${d(terrain)}"/><path class="profile-road" d="${d(road)}"/><path class="station-mark" d="M${x} ${top}V162"/><circle class="station-dot" cx="${x}" cy="${road[index][1]}" r="5"/><text class="svg-label" x="42" y="32">terrain</text><text class="svg-value" x="42" y="46">proposed road</text>`;}
function drawSection(){const svg=$('#section-view'),c=260,half=Math.min(165,roadWidth()*5),median=state.median*5,shoulder=state.shoulder*5,lane=state.lane*10,slope=24*Math.sin(state.station/100*5.3),y=91-state.elevation*4,x=c-half,w=half*2;svg.innerHTML=`<path class="section-terrain" d="M0 ${86-slope}L${x-20} ${y+22}L${x} ${y+8}L${x+w} ${y+8}L${x+w+25} ${y+26}L520 ${116+slope}V190H0Z"/><rect class="section-road" x="${x}" y="${y}" width="${w}" height="13"/><rect class="section-median" x="${c-median/2}" y="${y-4}" width="${median}" height="17"/><path d="M${x+shoulder+lane} ${y}v13M${x+w-shoulder-lane} ${y}v13" stroke="#ded6bc" stroke-dasharray="4 3"/><path class="dimension" d="M${x} 145H${x+w}M${x} 140v10M${x+w} 140v10"/><text class="svg-value" text-anchor="middle" x="${c}" y="162">${roadWidth()} blocks overall</text><text class="svg-label" text-anchor="middle" x="${c}" y="${y-10}">median</text>`;}
function drawModel(){$('#model-view').innerHTML=`<div class="model-scene">${state.terrain==='hidden'?'':`<div class="model-ground" style="opacity:${state.terrain==='cutaway'?'.38':'1'}"></div>`}<div class="model-road" style="height:${Math.max(42,roadWidth()*1.65)}px"></div><div class="model-bridge"></div><div class="model-station" style="left:${12+state.station*.75}%"><i></i><span>${Math.round(metrics().length*state.station/100)} m</span></div></div>`;}
function renderReview(){$('#review-table').innerHTML=Object.entries(alternatives).map(([key,a])=>{const m=metrics(key);return `<tr data-selected="${key===state.alternative}"><td><strong>${a.name}</strong></td><td>${m.length} m</td><td>${m.grade}%</td><td>${a.intervention}</td><td>Locked · 42 m straight</td></tr>`;}).join('');const a=alternatives[state.alternative],m=metrics();$('#review-choice').textContent=a.name;$('#review-summary').textContent=summaries[state.alternative];$('#review-details').innerHTML=`<dt>Route length</dt><dd>${m.length} m</dd><dt>Maximum grade</dt><dd>${m.grade}%</dd><dt>Overall section</dt><dd>${m.width} blocks</dd><dt>Terrain intervention</dt><dd>${a.intervention}</dd>`;}
function render(){renderAlternatives();bindAlternativeKeys();drawPlan();$('#plan-view').classList.toggle('stepping',state.stepping);drawProfile();drawSection();drawModel();renderReview();const m=metrics(),at=Math.round(m.length*state.station/100),readout=`${at} metres along the ${alternatives[state.alternative].name}; maximum grade ${m.grade} percent; ${m.width} blocks overall`;$('#station-output').textContent=`${at} m / ${m.length} m`;$('#station').setAttribute('aria-valuetext',readout);$('#plan-view').setAttribute('aria-label',`Plan view at ${readout}`);$('#profile-view').setAttribute('aria-label',`Profile at ${readout}`);$('#section-view').setAttribute('aria-label',`Cross-section at ${readout}`);$('#section-station').textContent=`At ${at} m`;$('#curve-output').textContent=`${state.curve>0?'+':''}${state.curve} blocks`;$('#elevation-output').textContent=`${state.elevation>0?'+':''}${state.elevation} blocks`;$('#plan-view').hidden=state.view!=='plan';$('#model-view').hidden=state.view!=='model';}
function dirty(){const n=$('#save-state');n.dataset.state='unsaved';n.innerHTML='<i></i> Unsaved changes';}
function toast(message){const n=$('#toast');n.textContent=message;n.hidden=false;clearTimeout(toast.timer);toast.timer=setTimeout(()=>n.hidden=true,2200);}
function panel(name){$$('[data-panel]').forEach(p=>p.hidden=p.dataset.panel!==name);$$('[data-workflow]').forEach(b=>{if(b.dataset.workflow===name)b.setAttribute('aria-current','step');else b.removeAttribute('aria-current');});window.scrollTo(0,0);}
function bindAlternativeKeys(){const cards=$$('.alternative-card');cards.forEach((card,index)=>{card.tabIndex=card.dataset.alternative===state.alternative?0:-1;card.onkeydown=event=>{let next;if(event.key==='ArrowRight'||event.key==='ArrowDown')next=(index+1)%cards.length;else if(event.key==='ArrowLeft'||event.key==='ArrowUp')next=(index-1+cards.length)%cards.length;else if(event.key==='Home')next=0;else if(event.key==='End')next=cards.length-1;else return;event.preventDefault();cards[next].click();requestAnimationFrame(()=>$$('.alternative-card')[next].focus());};});}
function sync(){for(const [id,key] of [['station','station'],['curve-offset','curve'],['road-elevation','elevation'],['lane-width','lane'],['median-width','median'],['shoulder-width','shoulder']])$('#'+id).value=state[key];$('#terrain-mode').value=state.terrain;for(const [id,key] of [['show-existing','existing'],['show-proposed','proposed'],['show-earthworks','earthworks'],['show-stepping','stepping']])$('#'+id).checked=state[key];}
$$('[data-workflow]').forEach(b=>b.onclick=()=>panel(b.dataset.workflow));$('#start-design').onclick=$('#back-to-design').onclick=()=>panel('design');$('#save-study').onclick=()=>{localStorage.setItem(KEY,JSON.stringify(state));const n=$('#save-state');n.dataset.state='saved';n.innerHTML='<i></i> Draft saved locally';toast('Road study saved in this browser.');};$('#reopen-study').onclick=()=>{const saved=localStorage.getItem(KEY);if(!saved)return toast('No saved road study yet.');Object.assign(state,JSON.parse(saved));sync();render();toast('Saved road study reopened.');};
for(const [id,key] of [['station','station'],['curve-offset','curve'],['road-elevation','elevation'],['lane-width','lane'],['median-width','median'],['shoulder-width','shoulder']])$('#'+id).oninput=e=>{state[key]=Number(e.target.value);if(key!=='station')dirty();render();};$('#terrain-mode').onchange=e=>{state.terrain=e.target.value;dirty();render();};for(const [id,key] of [['show-existing','existing'],['show-proposed','proposed'],['show-earthworks','earthworks'],['show-stepping','stepping']])$('#'+id).onchange=e=>{state[key]=e.target.checked;dirty();render();};$$('[data-view]').forEach(b=>b.onclick=()=>{state.view=b.dataset.view;$$('[data-view]').forEach(x=>x.setAttribute('aria-pressed',x===b));render();});$('#fit-route').onclick=()=>{state.view='plan';state.station=50;$('#station').value=50;$$('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x.dataset.view==='plan')));render();toast('Full route fitted in plan view.');};$('#approach-view').onclick=()=>{state.station=88;$('#station').value=88;render();toast('Moved to the bridge approach.');};
$('#export-study').onclick=()=>{const payload={schema:'praya.transport.study.v1',kind:'synthetic-road-study',constructionReady:false,worldBinding:null,selectedAlternative:state.alternative,parameters:state,measurements:metrics(),points:points(),notes:['Synthetic terrain and provisional local origin','Fixed bridge tie-in','No surveyed coordinates or world-write authority']},url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='transport-study-t001-review.json';a.click();URL.revokeObjectURL(url);toast('Review JSON exported.');};
sync();render();window.transportStatus=()=>({ready:true,...state,measurements:metrics(),panel:$$('[data-panel]').find(p=>!p.hidden)?.dataset.panel});
